### ISSUE TITLE
SSLType and CertificateFile are not valid keywords in imapstore sections

### ISSUE THREAD

**Issue by isaac-leonard-uni** [cemkeylan/mu-wizard#10]
When ever I've tried running muw add I get the following error
/Users/isaac/.mbsyncrc:17: keyword 'SSLType' is not recognized in IMAPStore sect
ions
/Users/isaac/.mbsyncrc:18: keyword 'CertificateFile' is not recognized in IMAPSt
ore sections
err: Log-on not successful.
err: It seems that either you have inputted the wrong password or server
err: settings, or there are requirements for your account out of the
err: control of mu-wizard.
err: /Users/isaac/.config/msmtp/config: No such file or directory
sed: 1: "/[Dd][Rr][Aa][Ff][Tt][S ...": extra characters at the end of q command
err: /Users/isaac/.config/msmtp/config: No such file or directory
I didn't mention it in my previous issue as I thought  I must have just been doing something wrong but I recently came back to trying to setup email in emacs and no matter what I can't find a solution.
The only thing I found said that removing excess newlines above SSLType would fix but there are no excess newlines being inserted, I've checked the source  code and output file before its deleted to ensure that no extra newline is there.
Do you know what could be causing this, it seems to happen with any email provider.
Commenting those lines out in the source causes the error to disappear, muw add then waits for a bit, making connections and then says that imap to the server failed with an unexpected EOF
That occurs with multiple email providers too.

**Comment by cemkeylan** [comment]
Can you provide more information on your system? These should be helpful:
- `mbsync --version`
- `sed --version`

Can you also provide `~/.mbsyncrc`? You can redact information you deem sensitive.

**Comment by isaac-leonard-uni** [comment]
mbsync is version 1.4.2, sed --version gives an error illegal option
I did some more digging, installing mbsync from home-brew changes the error to something about an invalid parameter, I'll post that in a second, building isync / mbsync from source however gives the error I said above in the original comment, mbsync --version gives 1.4.2 for both but the error specified by the home-brew version was patched in version 1.4.1 according to sourceforge.net

**Comment by isaac-leonard-uni** [comment]
Heres the error from the mbsync version from home-brew
Error performing SASL authentication step: SASL(-7): invalid parameter supplied:
 Parameter Error in /BuildRoot/Library/Caches/com.apple.xbs/Sources/passwordserv
er_saslplugins/passwordserver_saslplugins-192.30.1/plain_clienttoken.c near line
 195
Log-on not successful.
It seems that either you have inputted the wrong password or server
settings, or there are requirements for your account out of the
control of mu-wizard.
/Users/isaac/.config/msmtp/config: No such file or directory
sed: 1: "/[Dd][Rr][Aa][Ff][Tt][S ...": extra characters at the end of q command
/Users/isaac/.config/msmtp/config: No such file or directory

**Comment by cemkeylan** [comment]
Can you reproduce in the latest master?

**Comment by isaac-leonard-uni** [comment]
Doing so gives the same error as before
/Users/isaac/.mbsyncrc:18: keyword 'SSLType' is not recognized in IMAPStore sections
/Users/isaac/.mbsyncrc:19: keyword 'CertificateFile' is not recognized in IMAPStore sections
L
It seems as though when I use the home-brew version of isync, I get prompted for my gpg password where as the built from source version doesn't reach that point

**Comment by isaac-leonard-uni** [comment]
If I manually create an empty ~/.config/msmtp/config file I get this error with the home-brew version of isync
Error performing SASL authentication step: SASL(-7): invalid parameter supplied:
 Parameter Error in /BuildRoot/Library/Caches/com.apple.xbs/Sources/passwordserv
er_saslplugins/passwordserver_saslplugins-192.30.1/plain_clienttoken.c near line
 195
Log-on not successful.
It seems that either you have inputted the wrong password or server
settings, or there are requirements for your account out of the
control of mu-wizard.
/usr/local/bin/muw: line 389:  3423 Terminated: 15          { mbsync -l "$title"
 || { err "Log-on not successful." "It seems that either you have inputted the w
rong password or server" "settings, or there are requirements for your account o
ut of the" "control of mu-wizard."; delete "$title"; kill 0; }; }
      3424                       | sed 's|/|.|g' > /tmp/mbsync-boxes
Terminated: 15

**Comment by cemkeylan** [comment]
Instead of creating empty files, just try removing `~/.mbsyncrc` and `~/.config/msmtp/config`.

**Comment by isaac-leonard-uni** [comment]
It doesn't change it

**Comment by cemkeylan** [comment]
Okay, I could reproduce your issue after skeeming through the source code of `isync`, and can say that this is an `mbsync` issue. It seems you have built mbsync without SSL and SASL support, therefore it doesn't recognize `SSLType` and `CertificateFile` keywords. You can fix this by building `isync` with SSL and SASL support:

```
./configure \
    --with-ssl \
    --with-sasl

make
make install
```

**Comment by isaac-leonard-uni** [comment]
So that seems to fix the original issue however now I'm getting the same error as I do from the home-brew version
Error performing SASL authentication step: SASL(-7): invalid parameter supplied: Parameter Error in
/BuildRoot/Library/Caches/com.apple.xbs/Sources/passwordserver_saslplugins/passwordserver_saslplugin
s-192.30.1/plain_clienttoken.c near line 195
I feel like that might mean something is broken on my Mac but not sure.
Should I open a new issue as the original problem seems to be solved?

**Comment by isaac-leonard-uni** [comment]
I'll upgrade my Mac to BigSir later today and see if that fixes anything

**Comment by cemkeylan** [comment]
You can also try:

```
./configure \
    --with-ssl \
    --with-sasl \
    --without-macos-keychain
```

**Comment by isaac-leonard-uni** [comment]
It still gives that error sorry

**Comment by cemkeylan** [comment]
Hopefully, the latest master fixes your issue by enforcing authentication mechanism to not use SASL.

**Comment by isaac-leonard-uni** [comment]
It looks like that's fixed and adding a blank msmtp config file gets rid of that warning, having the directory without the file doesn't though.
I'm still getting sed: 1: "/[Dd][Rr][Aa][Ff][Tt][S ...": extra characters at the end of q command
though but that's the only error now, I feel like I might have a different sed program to what you're expecting as trying to get its version failed as I posted above.
I'll investigate this and get back to you
Thank you for your help

**Comment by isaac-leonard-uni** [comment]
Got it all working
I had to follow this however
https://gist.github.com/andre3k1/e3a1a7133fded5de5a9ee99c87c6fa0d
It looks like Mac comes with the bsd version of sed but mu-wizard uses the gnu version

**Comment by isaac-leonard-uni** [comment]
Actually maybe not all done yet
running muw sync just gave this error
/usr/local/bin/muw: line 338: notify-send: command not found

**Comment by isaac-leonard-uni** [comment]
installing libnotify fixed that, now having issues with mu being called Mailutils on Mac with no alias for mu but that should be easily fixable

**Comment by isaac-leonard-uni** [comment]
So I fixed that however I now get this
mu: don't know what index is
Running mu help gives no mention of an index command and I can't find it in the docs

**Comment by isaac-leonard-uni** [comment]
Actually ignore my last few comments, home-brew does have mu, Mailutils is a separate program, there's also an editor called mu which confused me too, looks like its all working now
Thank you

**Comment by cemkeylan** [comment]
> It looks like that's fixed and adding a blank msmtp config file gets rid of that warning, having the directory without the file doesn't though.
> I'm still getting sed: 1: "/[Dd][Rr][Aa][Ff][Tt][S ...": extra characters at the end of q command
> though but that's the only error now, I feel like I might have a different sed program to what you're expecting as trying to get its version failed as I posted above.
> I'll investigate this and get back to you
> Thank you for your help
> 

Can you create a new issue for the `sed` problem? I want to ensure that `sed` calls are portable, so you actually shouldn't be needing gnu-sed.

**Comment by cemkeylan** [comment]
I'll be closing this issue now, glad to see you got it working!
