### ISSUE TITLE
Mu4e fails without prompting for a password for pass when sending or updating mail

### ISSUE THREAD

**Issue by isaac-leonard-uni** [cemkeylan/mu-wizard#12]
I'm not really sure if this is a muw issue or a mu4e issue but the only references to it that I can find are years old and don't seem to give clear solutions.
If I use pass to get any password then mu4e will work perfectly fine afterwards as pass will temporarily cache my login, if I don't do this however then mu4e will fail fetching email with an message 
[mu4e] Update process returned with non-zero exit code
When trying to send mail it will display a full error buffer with more information.
I don't know if this is a mbsync and msmtp configuration issue from muw or a mu4e issue.

**Comment by cemkeylan** [comment]
Can you please post the full log buffer?

**Comment by isaac-leonard-uni** [comment]
I'm not really sure if this is still an issue.
It seems like it was caused because I didn't have gig-agent set up to work with emacs and so it would silently fail to decrypt my passwords.
I've got it almost perfectly working now however it still requires me to input my password from the terminal (the same termianal tab that emacs is running in) instead of emacs itself however this is not a major issue.
To get this behaviour I put this in my gpg-agent.conf file
allow-emacs-pinentry
allow-loopback-pinentry

And I put this in my init.el
(setq epg-pinentry-mode 'loopback)
(setq mu4e-get-mail-command (format "INSIDE_EMACS=%s mbsync -a" emacs-version))
(use-package pinentry
  :config (pinentry-start))

**Comment by cemkeylan** [comment]
Alright, it seems to be a pinentry issue rather than an `mu4e` or `mu-wizard` issue. I don't consider configuring `pinentry` or `gpg-agent` to be a scope of this project, it's a rather complex system that every distribution and user has a different idea of. I will be closing this issue as it's not directly related to the project.

**Comment by isaac-leonard-uni** [comment]
It might be worth adding a note that they do need to be configured in the readme as I was only able to fix this issue the other day once I figured out what was going on.

**Comment by cemkeylan** [comment]
I personally use `pinentry-dmenu`, so I never had such an issue nor required such a piece of code, and issues that may arise are completely specific to one's setup. It's better for people to search previous Github issues than to clutter the README with rare issues not directly related with `mu-wizard` itself.
