### ISSUE TITLE
error: expected schema-version 452, but got 451; please use 'mu init'

### ISSUE THREAD

**Issue by rajudev** [cemkeylan/mu-wizard#14]
While trying to configure an account with muw I got this error while doing `muw sync <account>` 

`error: expected schema-version 452, but got 451; please use 'mu init'`

additional details.
Host: Debian Sid
mu-wizard version: 1.0.0-rc1
mu (mail indexer/searcher) version 1.6.10

**Comment by cemkeylan** [comment]
Well, this happens when the database schema of `mu` changes when you update it. Run `muw mu-init` to reindex the database.

**Comment by rajudev** [comment]
Thank you, this did the trick. 
Maybe you should add it in the README, to run `muw-init` after configuring the accounts and before running the sync
