### ISSUE TITLE
"File is missing: Cannot open load file, No such file or directory, mu4e"

### ISSUE THREAD

**Issue by bcmertz** [cemkeylan/mu-wizard#6]
Getting this error from emacs 28.0.50
mu version 1.4.15

From pacman -Ql mu it looks like mu4e is provided in /usr/share/emacs/site-lisp/mu4e

I tried adding (add-to-list 'load-path "/usr/share/emacs/site-lisp/mu4e") but it still isnt found correctly, perhaps I should file this bug with mu, any thoughts? Thanks!

**Comment by bcmertz** [comment]
Fixed the error with 

```
(load-file "~/.config/mu4e/mu4e-config.el")

(add-to-list 'load-path "~/.config/mu4e")
(add-to-list 'load-path "/usr/share/emacs/site-lisp/mu4e")
(use-package mu4e
  :load-path "/usr/share/emacs/site-lisp/mu4e"
  )

(require 'mu4e-config)

(use-package mu4e-config
  :after mu4e
  :load-path "~/.config/mu4e")
```

**Comment by bcmertz** [comment]
Still can't launch mu4e :confused:

**Comment by bcmertz** [comment]
This can probably be closed now, thank you!

**Comment by cemkeylan** [comment]
I think the problem may be adding those to your load-path, although I am not exactly sure. This would be a much simpler configuration. You don't need to add mu4e to your load-path, since it is in your `site-lisp` directory. Maybe this could simply work better?

```emacs-lisp
(use-package mu4e)
(use-package mu4e-config
    :after mu4e
    :load-path "~/.config/mu4e")
```

**Comment by bcmertz** [comment]
Thanks! This works with one change to add load-path to mu4e
