### ISSUE TITLE
Open repo permissions for new branches

### ISSUE THREAD

**Issue by bcmertz** [cemkeylan/mu-wizard#7]
It looks like the permissions on this repo prevented me from pushing a branch:

```
128 git … push -v --set-upstream origin bcm/muw-alerts\:refs/heads/bcm/muw-alerts
Pushing to github.com:cemkeylan/mu-wizard.git
ERROR: Permission to cemkeylan/mu-wizard.git denied to bcmertz.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I have no problem cloning, it's just pushing a branch to the remote that fails

**Comment by cemkeylan** [comment]
To create a pull request, it's better to fork the repository and push your changes to your own tree. I also accept patches from mail!
