### ISSUE TITLE
Specify minimum version for isync in readme

### ISSUE THREAD

**Issue by isaac-leonard-uni** [cemkeylan/mu-wizard#8]
A minimum version of  1.4.0 for isync / mbsync is required but is not specified in the readme.
The home-brew package manager on Mac and I believe a few linux package managers don't have the this version in there repositories yet so it might be helpful to add this to the requirements section and specify that isync should be built from source.

**Comment by cemkeylan** [comment]
I'm sorry, I was under the false impression that `Far/Near` syntax existed before version 1.4.0 and `Master/Slave` syntax was only depracated now. I have added a check for the isync version which uses the newer syntax if it is `>=1.4.0`. Latest version should not be required anymore, sorry for the inconvience.
